/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.domain.organisation

import android.os.Parcelable
import com.squareup.moshi.Json
import kotlinx.android.parcel.Parcelize
import java.io.Serializable

/**
 * 
 * @param id 
 * @param name 
 * @param type
 */
@Parcelize
data class Organization (
    val id: java.math.BigDecimal,
    val name: kotlin.String,
    val type: Type
) : Parcelable, Serializable {

    /**
    * 
    * Values: party,commission,watchers
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "party") party("party"),
    
        @Json(name = "commission") commission("commission"),
    
        @Json(name = "watchers") watchers("watchers");
    
    }

}

