/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.domain.organisation

import bg.dabulgaria.tibroish.persistence.remote.model.User

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param type
 */
data class Organization (
    val id: java.math.BigDecimal,
    val name: kotlin.String,
    val users: kotlin.collections.List<User>,
    val type: Type
) {

    /**
    * 
    * Values: party,commission,watchers
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "party") party("party"),
    
        @Json(name = "commission") commission("commission"),
    
        @Json(name = "watchers") watchers("watchers");
    
    }

}

