/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.PostDto
import bg.dabulgaria.tibroish.persistence.remote.model.UserDto

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param title 
 * @param contents 
 * @param author 
 * @param status 
 * @param topics 
 * @param users 
 * @param post 
 * @param url 
 * @param publishAt 
 */
data class BroadcastDto (
    val id: kotlin.String,
    val title: kotlin.String,
    val contents: kotlin.String,
    val author: UserDto,
    val status: BroadcastDto.Status,
    val topics: BroadcastDto.Topics,
    val users: kotlin.collections.List<UserDto>,
    val post: PostDto,
    val url: kotlin.String,
    val publishAt: java.time.OffsetDateTime
) {

    /**
    * 
    * Values: pending,processing,published,discarded
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "pending") pending("pending"),
    
        @Json(name = "processing") processing("processing"),
    
        @Json(name = "published") published("published"),
    
        @Json(name = "discarded") discarded("discarded");
    
    }

    /**
    * 
    * Values: admin,lawyer,validator,representative
    */
    enum class Topics(val value: kotlin.collections.List<kotlin.String>){
    
        @Json(name = "role.admin") admin(listOf("role.admin")),
        @Json(name = "role.lawyer") lawyer(listOf("role.lawyer")),
        @Json(name = "role.validator") validator(listOf("role.validator")),
        @Json(name = "role.representative") representative(listOf("role.representative"));
    
    }

}

