/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.Section
import bg.dabulgaria.tibroish.persistence.remote.model.Town

/**
 * 
 * @param id 
 * @param code 
 * @param name 
 * @param towns 
 * @param sections 
 */
data class CityRegion (
    val id: java.math.BigDecimal,
    val code: kotlin.String,
    val name: kotlin.String,
    val towns: kotlin.collections.List<Town>,
    val sections: kotlin.collections.List<Section>
) {

}

