/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.User

/**
 * 
 * @param id 
 * @param token 
 * @param owner 
 * @param isActive 
 * @param registeredAt 
 */
data class Client (
    val id: kotlin.String,
    val token: kotlin.String,
    val owner: User,
    val isActive: kotlin.Boolean,
    val registeredAt: java.time.OffsetDateTime
) {

}

