/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.domain.locations.CityRegionRemote
import bg.dabulgaria.tibroish.domain.locations.TownRemote

/**
 * 
 * @param cityRegions 
 * @param code 
 * @param name 
 * @param isAbroad 
 * @param id 
 * @param towns 
 * @param sectionsCount 
 */
data class CountryDto (
        val cityRegions: CityRegionRemote,
        val code: kotlin.String,
        val name: kotlin.String,
        val isAbroad: kotlin.Boolean,
        val id: java.math.BigDecimal,
        val towns: kotlin.collections.List<TownRemote>,
        val sectionsCount: java.math.BigDecimal
) {

}

