/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.MunicipalityDto

/**
 * 
 * @param code 
 * @param name 
 * @param isAbroad 
 * @param municipalities 
 */
data class ElectionRegionDto (
    val code: kotlin.String,
    val name: kotlin.String,
    val isAbroad: kotlin.Boolean,
    val municipalities: kotlin.collections.List<MunicipalityDto>
) {

}

