/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.domain.locations.Country

/**
 * 
 * @param id 
 * @param code 
 * @param name 
 * @param isAbroad 
 * @param sections 
 * @param sectionsCount 
 * @param voters 
 * @param countries 
 * @param stats 
 * @param admUnits 
 * @param municipalities 
 */
data class ElectionRegion (
        val id: java.math.BigDecimal,
        val code: kotlin.String,
        val name: kotlin.String,
        val isAbroad: kotlin.Boolean,
        val sections: kotlin.collections.List<Section>,
        val sectionsCount: java.math.BigDecimal,
        val voters: java.math.BigDecimal,
        val countries: kotlin.collections.List<Country>,
        val stats: StatsDto,
        val admUnits: kotlin.collections.List<kotlin.Any>,
        val municipalities: kotlin.collections.List<Municipality>
) {

}

