/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.PictureDto
import bg.dabulgaria.tibroish.persistence.remote.model.UserDto

/**
 * 
 * @param id 
 * @param title 
 * @param slug 
 * @param contents 
 * @param author 
 * @param isListed 
 * @param publishAt 
 * @param picture 
 */
data class PostDto (
    val id: kotlin.String,
    val title: kotlin.String,
    val slug: kotlin.String,
    val contents: kotlin.String,
    val author: UserDto,
    val isListed: kotlin.Boolean,
    val publishAt: java.time.OffsetDateTime,
    val picture: PictureDto? = null
) {

}

