/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.PartyDto

/**
 * 
 * @param party 
 * @param validVotesCount 
 * @param machineVotesCount 
 * @param nonMachineVotesCount 
 * @param invalidVotesCount 
 */
data class ProtocolResultDto (
    val party: PartyDto,
    val validVotesCount: java.math.BigDecimal,
    val machineVotesCount: java.math.BigDecimal? = null,
    val nonMachineVotesCount: java.math.BigDecimal? = null,
    val invalidVotesCount: java.math.BigDecimal? = null
) {

}

