/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.ProtocolResultDto

/**
 * 
 * @param results 
 * @param votersCount 
 * @param validVotesCount 
 * @param invalidVotesCount 
 * @param machineVotesCount 
 */
data class ProtocolResultsDto (
    val results: kotlin.collections.List<ProtocolResultDto>,
    val votersCount: java.math.BigDecimal? = null,
    val validVotesCount: java.math.BigDecimal? = null,
    val invalidVotesCount: java.math.BigDecimal? = null,
    val machineVotesCount: java.math.BigDecimal? = null
) {

}

