/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.Protocol
import bg.dabulgaria.tibroish.persistence.remote.model.User

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param protocol 
 * @param actor 
 * @param action 
 * @param payload 
 * @param timestamp 
 */
data class ProtocolAction (
    val id: kotlin.String,
    val protocol: Protocol,
    val actor: User,
    val action: ProtocolAction.Action,
    val payload: kotlin.Any,
    val timestamp: java.time.OffsetDateTime
) {

    /**
    * 
    * Values: send,assign,reject,approve,publish,replace,populate
    */
    enum class Action(val value: kotlin.String){
    
        @Json(name = "send") send("send"),
    
        @Json(name = "assign") assign("assign"),
    
        @Json(name = "reject") reject("reject"),
    
        @Json(name = "approve") approve("approve"),
    
        @Json(name = "publish") publish("publish"),
    
        @Json(name = "replace") replace("replace"),
    
        @Json(name = "populate") populate("populate");
    
    }

}

