/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.PictureDto
import bg.dabulgaria.tibroish.persistence.remote.model.ProtocolResultsDto
import bg.dabulgaria.tibroish.persistence.remote.model.SectionDto
import bg.dabulgaria.tibroish.persistence.remote.model.UserDto

/**
 * 
 * @param id 
 * @param section 
 * @param pictures 
 * @param assignees 
 * @param status 
 * @param results 
 * @param author 
 */
data class ProtocolDto (
    val id: java.math.BigDecimal,
    val section: SectionDto,
    val pictures: kotlin.collections.List<PictureDto>,

) {

}

