/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.CityRegionDto
import bg.dabulgaria.tibroish.persistence.remote.model.ElectionRegionDto
import bg.dabulgaria.tibroish.persistence.remote.model.TownDto

/**
 * 
 * @param id 
 * @param code 
 * @param place 
 * @param votersCount 
 * @param isMachine 
 * @param isMobile 
 * @param electionRegion 
 * @param town 
 * @param cityRegion 
 */
data class SectionDto (
    val id: kotlin.String,
    val code: kotlin.String,
    val place: kotlin.String,
    val votersCount: java.math.BigDecimal,
    val isMachine: kotlin.Boolean,
    val isMobile: kotlin.Boolean,
    val electionRegion: ElectionRegionDto,
    val town: TownDto,
    val cityRegion: CityRegionDto
) {

}

