/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.CityRegion
import bg.dabulgaria.tibroish.persistence.remote.model.ElectionRegion
import bg.dabulgaria.tibroish.persistence.remote.model.Protocol
import bg.dabulgaria.tibroish.persistence.remote.model.StatsDto
import bg.dabulgaria.tibroish.persistence.remote.model.Town
import bg.dabulgaria.tibroish.persistence.remote.model.Violation

/**
 * 
 * @param id 
 * @param code 
 * @param place 
 * @param votersCount 
 * @param isMachine 
 * @param isMobile 
 * @param isShip 
 * @param electionRegion 
 * @param town 
 * @param cityRegion 
 * @param protocols 
 * @param violations 
 * @param stats 
 * @param results 
 */
data class Section (
    val id: kotlin.String,
    val code: kotlin.String,
    val place: kotlin.String,
    val votersCount: java.math.BigDecimal,
    val isMachine: kotlin.Boolean,
    val isMobile: kotlin.Boolean,
    val isShip: kotlin.Boolean,
    val electionRegion: ElectionRegion,
    val town: Town,
    val cityRegion: CityRegion,
    val protocols: kotlin.collections.List<Protocol>,
    val violations: kotlin.collections.List<Violation>,
    val stats: StatsDto,
    val results: kotlin.collections.List<java.math.BigDecimal>
) {

}

