/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model


/**
 * 
 * @param violationsCount 
 * @param sectionsWithProtocols 
 * @param sectionsCount 
 * @param sectionsWithResults 
 * @param voters 
 * @param validVotes 
 * @param invalidVotes 
 */
data class StatsDto (
    val violationsCount: java.math.BigDecimal? = null,
    val sectionsWithProtocols: java.math.BigDecimal? = null,
    val sectionsCount: java.math.BigDecimal? = null,
    val sectionsWithResults: java.math.BigDecimal? = null,
    val voters: java.math.BigDecimal? = null,
    val validVotes: java.math.BigDecimal? = null,
    val invalidVotes: java.math.BigDecimal? = null
) {

}

