/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.domain.locations.SectionRemote

/**
 * 
 * @param id 
 * @param chunks 
 * @param user 
 * @param streamUrl 
 * @param broadcastUrl 
 * @param isStreaming 
 * @param isAssigned 
 * @param createdAt 
 * @param section 
 * @param updatedAt 
 */
data class Stream (
        val id: kotlin.String,
        val chunks: kotlin.collections.List<StreamChunk>,
        val user: User,
        val streamUrl: kotlin.String,
        val broadcastUrl: kotlin.String,
        val isStreaming: kotlin.Boolean,
        val isAssigned: kotlin.Boolean,
        val createdAt: java.time.OffsetDateTime,
        val section: SectionRemote? = null,
        val updatedAt: java.time.OffsetDateTime? = null
) {

}

