/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

/**
 * 
 * @param section 
 * @param id 
 * @param isStreaming 
 * @param isAssigned 
 * @param streamUrl 
 * @param broadcastUrl 
 * @param viewUrl 
 */
data class StreamDto (
    //val section: SectionDto,
    val id: kotlin.String,
    val isStreaming: kotlin.Boolean,
    val isAssigned: kotlin.Boolean,
    val streamUrl: kotlin.String,
    val broadcastUrl: kotlin.String,
    val viewUrl: kotlin.String? = null
) {

}

