/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.Section
import bg.dabulgaria.tibroish.persistence.remote.model.Stream
import bg.dabulgaria.tibroish.persistence.remote.model.User

/**
 * 
 * @param id 
 * @param stream 
 * @param section 
 * @param author 
 * @param isActive 
 * @param startTime 
 * @param url 
 * @param endTime 
 */
data class StreamChunk (
    val id: kotlin.String,
    val stream: Stream,
    val section: Section,
    val author: User,
    val isActive: kotlin.Boolean,
    val startTime: java.time.OffsetDateTime,
    val url: kotlin.String? = null,
    val endTime: java.time.OffsetDateTime? = null
) {

}

