/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.CityRegion
import bg.dabulgaria.tibroish.persistence.remote.model.Country
import bg.dabulgaria.tibroish.persistence.remote.model.Municipality
import bg.dabulgaria.tibroish.persistence.remote.model.Section
import bg.dabulgaria.tibroish.persistence.remote.model.Violation

/**
 * 
 * @param id 
 * @param code 
 * @param name 
 * @param country 
 * @param municipality 
 * @param cityRegions 
 * @param sections 
 * @param violations 
 */
data class Town (
    val id: java.math.BigDecimal,
    val code: java.math.BigDecimal,
    val name: kotlin.String,
    val country: Country,
    val municipality: Municipality,
    val cityRegions: kotlin.collections.List<CityRegion>,
    val sections: kotlin.collections.List<Section>,
    val violations: kotlin.collections.List<Violation>
) {

}

