/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.CityRegionDto
import bg.dabulgaria.tibroish.persistence.remote.model.CountryDto
import bg.dabulgaria.tibroish.persistence.remote.model.MunicipalityDto

/**
 * 
 * @param id 
 * @param name 
 * @param cityRegions 
 * @param country 
 * @param municipality 
 */
data class TownDto (
    val id: java.math.BigDecimal,
    val name: kotlin.String,
    val cityRegions: kotlin.collections.List<CityRegionDto>,
    val country: CountryDto,
    val municipality: MunicipalityDto
) {

}

