/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.domain.organisation.OrganizationDto

/**
 * 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param phone 
 * @param pin 
 * @param organization 
 * @param firebaseUid 
 * @param id 
 * @param hasAgreedToKeepData 
 */
data class UserDto (
        val firstName: kotlin.String,
        val lastName: kotlin.String,
        val email: kotlin.String,
        val phone: kotlin.String,
        val pin: kotlin.String,
        val organization: OrganizationDto,
        val firebaseUid: kotlin.String,
        val id: kotlin.String,
        val hasAgreedToKeepData: kotlin.Boolean? = null
) {

}

