/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.User
import bg.dabulgaria.tibroish.persistence.remote.model.Violation

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param violation 
 * @param actor 
 * @param type 
 * @param payload 
 * @param timestamp 
 */
data class ViolationUpdate (
    val id: kotlin.String,
    val violation: Violation,
    val actor: User,
    val type: ViolationUpdate.Type,
    val payload: kotlin.Any,
    val timestamp: java.time.OffsetDateTime
) {

    /**
    * 
    * Values: send,assign,reject,process,publish,unpublish
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "send") send("send"),
    
        @Json(name = "assign") assign("assign"),
    
        @Json(name = "reject") reject("reject"),
    
        @Json(name = "process") process("process"),
    
        @Json(name = "publish") publish("publish"),
    
        @Json(name = "unpublish") unpublish("unpublish");
    
    }

}

