/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.persistence.remote.model

import bg.dabulgaria.tibroish.persistence.remote.model.UserDto

/**
 * 
 * @param id 
 * @param author 
 * @param text 
 * @param createdAt 
 */
data class ViolationCommentDto (
    val id: kotlin.String,
    val author: UserDto,
    val text: kotlin.String,
    val createdAt: java.time.OffsetDateTime
) {

}

