/**
* Ti Broish API
* Ti Broish API is built for clients sending in election results data in Bulgaria
*
* OpenAPI spec version: 0.1
* Contact: team@dabulgaria.bg
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package bg.dabulgaria.tibroish.domain.image

import java.io.Serializable


/**
 * 
 * @param id 
 * @param url 
 * @param path 
 * @param rotation 
 */
data class PictureDto (
    val id: String,
    val url: String,
    val path: String,
    val rotation: Int): Serializable
